from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
import itertools
import pandas as pd
import os 
import pywhatkit as py

#message to single user
py.sendwhatmsg("+919821710650","whatsappmssg",21,39,15,True,2)

#message to group
py.sendwhatmsg_to_group("LPpeVLMJaJjEKQOEWpQsxr","this message is generated by python script using pywhatkit and send automatically by automation \n -- rose",21,40,15,True,2)

#message to multi group
groups = ["LPpeVLMJaJjEKQOEWpQsxr", "Jmbs7kfai3XDkNVtFWHj2H"]
for i in groups:
    py.sendwhatmsg_to_group_instantly(i, "Hey Guys, \n its Rose")
    
os.environ['PATH'] += "D:\working"
driver = webdriver.Chrome()
driver.get('https://web.whatsapp.com')
time.sleep(25)

df = pd.read_csv("workbook.csv")
Name = df['Name'].tolist()
Number = df["MobileNo"].tolist()

    
# same message, different user
for i, j in zip(Number, Name):
    Search = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH,'//*[@id="side"]/div[1]/div/div/div[2]/div/div[2]')))
    time.sleep(2)
    
    Search.send_keys(i)
    time.sleep(1)
    Search.send_keys(Keys.ENTER)
    time.sleep(3)
    Message = driver.find_elements(By.XPATH,'//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div[1]')
    time.sleep(2)
    #//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div[1]
    k = "hello, its jerry"
    Message[0].send_keys('Hello ' + str(j)+ ',')
    time.sleep(1)
    Message[0].send_keys(Keys.SHIFT, Keys.ENTER)
    Message[0].send_keys(Keys.SHIFT, Keys.ENTER)
    Message[0].send_keys('This is just a test to see if you got a test message. \n' + str(k))
    time.sleep(1)
    Message[0].send_keys(Keys.ENTER)
    print('Sent to ' + str(j)) 
    
#particular message to particular user   
message = df["Messages"].tolist()
for i, j,l in zip(Number, Name, message):
    Search = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH,'//*[@id="side"]/div[1]/div/div/div[2]/div/div[2]')))
    time.sleep(2)
    
    Search.send_keys(i)
    time.sleep(1)
    Search.send_keys(Keys.ENTER)
    time.sleep(3)
    Message = driver.find_elements(By.XPATH,'//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div[1]')
    time.sleep(2)
    #//*[@id="main"]/footer/div[1]/div/span[2]/div/div[2]/div[1]/div/div[1]
    k = "-- Rose"
    Message[0].send_keys('Hello ' + str(j)+ ',')
    time.sleep(1)
    Message[0].send_keys(Keys.SHIFT, Keys.ENTER)
    Message[0].send_keys(Keys.SHIFT, Keys.ENTER)
    Message[0].send_keys(str(l)+'\n' + str(k))
    time.sleep(1)
    Message[0].send_keys(Keys.ENTER)
    print('Sent to ' + str(j)) 
    
    